export default class Languages {

    static BD = {

        //Common-------------------------------------------------------------------------------------------------------------------------
        description: 'বিবরণ',
        select_division: 'বিভাগ নির্বাচন করুন',
        select_district: 'জেলা নির্বাচন করুন',
        select_thana: 'থানা/উপজেলা নির্বাচন করুন',
        title: 'শিরোনাম',
        male: 'পুরুষ',
        female: 'মহিলা',
        both: 'উভয়',
        address: 'ঠিকানা',
        mobile_number_to_contact: "মোবাইল নাম্বার(যোগাযোগ করার জন্য)",
        current_division_district_thana: "বিভাগ,জেলা,থানা",
        contact_info: 'যোগাযোগ',
        photos: 'ছবি',
        post: 'পোস্ট',
        next: 'পরবর্তী ধাপ',
        choose: 'বেছে নিন',
        money_amount: 'টাকার পরিমান',
        educational_qualifications: 'Educational Qualifications',

        //Swap -------------------------------------------------------------------------------------------------------------------------

        swap_of_products: "জিনিসপত্রের অদলবদল",
        what_category_of_products_do_you_want_to_exchange: "আপনি কোন ক্যাটাগরির জিনিস অদলবদল করতে চাচ্ছেন ? ",
        name_of_the_products: "জিনিসটি /জিনিসগুলোর নাম",
        condition_of_the_products: "জিনিসটি বা জিনিসগুলো কি অবস্থায় আছে ?",
        new: "নতুন",
        used_excellent_condition: "ব্যবহৃত- খুব ভালো অবস্থা",
        used_good_condition: "ব্যবহৃত- ভালো অবস্থা",
        used_acceptable: "ব্যবহৃত- মোটামোটি",
        damaged: "পুরান/ভাঙ্গা",
        description_of_the_products: "জিনিসটির বিবরণ",
        what_category_of_products_do_you_want_to_exchange_with: "আপনি কোন ক্যাটাগরির জিনিসের সাথে অদলবদল করতে চাচ্ছেন ?",
        write_something_about_swaps: "অদলবদল সম্পর্কে কিছু লিখুন ",
        if_you_have_more_than_one_product: 'উদাহরণস্বরূপ - মোবাইল, ল্যাপটপ',
        max_photo_upload_message: '*** আপনি সর্বোচ্চ ৫টি ছবি আপলোড করতে পারবেন ; ছবি আপলোড করতে না চাইলে পরবর্তী ধাপে চলে যান !',
        more_than_one_mobile_numner: 'উদাহরণস্বরূপ: ০১৮৯৫৫৩২১১৯, ০১৭৯০০৮১২২৩',
        final_post: 'পোস্ট করুন',
        swap_product: 'অদলবদল পণ্য',
        swap_with_money: 'টাকা দিয়ে',
        swap_with_product: 'পণ্য দিয়ে',
        swap_option: 'অদলবদল করুন',

        //Lost -------------------------------------------------------------------------------------------------------------------------
        lost: 'হারানো গিয়েছে',
        lost_title: 'শিরোনাম (কি হারানো গিয়েছে?)',
        can_you_guess_where_did_it_happen: 'কোথায় হারানো গিয়েছে(অনুমানের ভিওিতে)? বিভাগ,জেলা,থানা',

        //Found -------------------------------------------------------------------------------------------------------------------------
        found: 'পাওয়া গিয়েছে',
        found_title: 'শিরোনাম (কি পাওয়া  গিয়েছে?)',

        //Job -------------------------------------------------------------------------------------------------------------------------
        recruitment_advertisement: 'চাকরির নিয়োগ বিজ্ঞাপন',
        job_category: 'চাকুরীর ক্যাটাগরি',
        educational_qualifications: 'শিক্ষাগত যোগ্যতা',
        gender: 'লিঙ্গ',
        salary: 'Salary',
        negotiable: 'আলোচনা সাপেক্ষে',
        fixed: 'নির্দিষ্ট',
        range: 'নির্দিষ্ট পরিসীমা',
        job_requirements: 'চাকরির প্রয়োজনীয়',
        to: 'থেকে',

        //Business Introduction ---------------------------------------------------------------------------------------------------------------------------
        food_business_introduction: 'ব্যব্সার পরিচিতি ',
        food_business_name: 'নাম (আপনার ব্যবসা প্রতিষ্ঠানের নাম)',
        type_of_food_business: 'ব্যব্সার ধরণ',
        food_list: 'খাবারের তালিকা',
        open_close_schedule: 'খোলা-বন্ধের সময়সূচি ',
        food_list_writting_suggest: 'উদাহরণস্বরূপ - খাবারের নাম ১, খাবারের নাম ২...',

        //Blood Needed ----------------------------------------------------------------------------------------------------------------------------
        blood_needed: 'রক্তের প্রয়োজন',
        blood_group: 'রক্তের গ্রুপ',
        how_many_bags_of_blood_are_needed: 'কত ব্যাগ রক্তের প্রয়োজন',
        date_of_blood_donation: 'রক্ত দানের তারিখ',
        where_to_donate_blood: 'কোথায় রক্ত দিতে হবে',


        //Teachning ----------------------------------------------------------------------------------------------------------------------------
        Want_to_teach: 'পড়াতে চাই',
        your_name: 'আপনার নাম',
        which_class_of_students_do_you_want_to_teach: 'আপনার কোন শ্রেণীর শিক্ষার্থী পড়াতে ইচ্ছুক',
        interested_subject_name: 'আপনি কোন বিষয় পড়াতে আগ্রহী',
        where_willing_to_teach: 'কোথায় পড়াতে ইচ্ছুক',
        medium: 'মাধ্যম',
        english: 'ইংরেজি',
        bangla: 'বাংলা',
        arabic: 'আরবি',
        both_en_bn: 'ইংরেজি ও বাংলা',
        one_class: '১ম শ্রেণী',
        two_class: '২য় শ্রেণী',
        three_class: '৩য় শ্রেণী',
        four_class: '৪র্থ শ্রেণী',
        five_class: '৫ম শ্রেণী',
        six_class: '৬ষ্ঠ শ্রেণী',
        seven_class: '৭ম শ্রেণী',
        eight_class: '৮ম শ্রেণী',
        nine_class: '৯ম শ্রেণী',
        ten_class: '১০ম শ্রেণী',
        eleven_class: 'একাদশ শ্রেণী',
        twelve_class: 'দ্বাদশ শ্রেণী',
        others_class: 'অন্যান্য',
        subjects_name: 'উদাহরণস্বরূপ: su, subject name 2',
        your_age: 'আপনার বয়স',
        you_can_write_avobe_twelve_class_subject: 'কিছু অবিদ্যমান ??, আপনি এখানে লিখতে পারেন',

    };
    static EN = {
        //Common-------------------------------------------------------------------------------------------------------------------------
        description: 'Description',
        select_division: 'Select Division',
        select_district: 'Select District',
        select_thana: 'Select Thana / Upazila',
        title: 'Title',
        male: 'Male',
        female: 'Female',
        both: 'Both',
        address: 'Address',
        mobile_number_to_contact: "Mobile number (to contact)",
        current_division_district_thana: "Division, District, Thana",
        choose: 'C h o o s e',
        next: 'N E X T',
        photos: 'Photo/s',
        contact_info: 'Contact',
        post: 'Post',
        money_amount: 'Amount of money',
        educational_qualifications: 'Educational Qualifications',
        final_post: 'P O S T',


        //Swap-------------------------------------------------------------------------------------------------------------------------
        swap_of_products: "SWAP OF PRODUCTS",
        what_category_of_products_do_you_want_to_exchange: "What's your product category ?",
        name_of_the_products: "Name of the product/s",
        condition_of_the_products: "Condition of the product/s",
        new: "New",
        used_excellent_condition: "Used-Excellent Condition",
        used_good_condition: "Used-Good Condition",
        used_acceptable: "Used-Acceptable",
        damaged: "Damaged",
        description_of_the_products: "Describe your product/s",
        what_category_of_products_do_you_want_to_exchange_with: "Category of product/s ?",
        write_something_about_swaps: "Write something about swaps",
        if_you_have_more_than_one_product: 'For example - mobile, laptop',
        max_photo_upload_message: '*** You can upload a maximum of 5 images; If you do not want to upload images, go to the next step !',
        more_than_one_mobile_numner: 'Example: 01895532119, 01790081223',
        swap_product: 'Swappable Product',
        swap_with_money: 'Money',
        swap_with_product: 'Product/s',
        swap_option: 'EXCHANGE WITH',

        //Lost -------------------------------------------------------------------------------------------------------------------------
        lost: 'Lost',
        lost_title: 'Title (What have you lost)??',
        can_you_guess_where_did_it_happen: 'Where have you lost?',

        //Found -------------------------------------------------------------------------------------------------------------------------
        found: 'Found',
        found_title: 'Title (What have you found)??',
        where_have_you_found_it: 'Where have you found?',

        //Job ---------------------------------------------------------------------------------------------------------------------------
        recruitment_advertisement: 'Recruitment Advertisement',
        job_category: 'Job Category',
        gender: 'Gender',
        salary: 'Salary',
        negotiable: 'Negotiable',
        fixed: 'Fixed',
        range: 'Range',
        job_requirements: 'Job Requirements',
        to: 'TO',

        //Food Business Introduction ---------------------------------------------------------------------------------------------------------------------------
        food_business_introduction: 'Food Business Introduction',
        food_business_name: 'Name (your business name)',
        type_of_food_business: 'Type of business',
        food_list: 'Food list',
        open_close_schedule: 'Open-Close Schedule',
        food_list_writting_suggest: 'Example - Food 1, Food 2',

        //Blood Needed ----------------------------------------------------------------------------------------------------------------------------
        blood_needed: 'Blood Needed',
        blood_group: 'Blood group',
        how_many_bags_of_blood_are_needed: 'How many bags of blood are needed',
        date_of_blood_donation: 'Date of blood donation',
        where_to_donate_blood: 'Where to donate blood',

        //Teachning ----------------------------------------------------------------------------------------------------------------------------
        Want_to_teach: 'Want To Teach',
        your_name: 'Your name',
        which_class_of_students_do_you_want_to_teach: 'Which class of students do you want to teach',
        interested_subject_name: 'Interested subject name',
        where_willing_to_teach: 'Where willing to teach (area name)',
        medium: 'Medium',
        english: 'English',
        bangla: 'Bangla',
        arabic: 'Arabic',
        both_en_bn: 'English & Bangla',
        one_class: '1st class',
        two_class: '2nd Class',
        three_class: '3rd Class',
        four_class: '4th Class',
        five_class: '5th Class',
        six_class: '6th Class',
        seven_class: '7th Class',
        eight_class: '8th Class',
        nine_class: '9th Class',
        ten_class: '10th Class',
        eleven_class: '11th Class',
        twelve_class: '12th Class',
        others_class: 'Others',
        subjects_name: 'Example: subject name 1, subject name 2',
        your_date_of_birth: 'Your date of birth',
        you_can_write_avobe_twelve_class_subject: 'Something missing ??, you can write here',

    };
}